# configured by following official documentation at: https://alacritty.org/config-alacritty.html
# color theme copied in: https://github.com/alacritty/alacritty-theme/tree/master/themes


[window]
decorations = "Full"
opacity = 0.94
blur = true
title = "👋 Haruka~"
padding.x = 10
padding.y = 10
dimensions = {columns = 100, lines = 46}

[font]
normal = {family = "MesloLGS NF", style = "Regular"}
size = 12.8
offset = {x = 1, y = 2}

# Colors (Snazzy)

# Default colors
[colors.primary]
background = '#282a36'
foreground = '#eff0eb'

# Normal colors
[colors.normal]
black   = '#282a36'
red     = '#ff5c57'
green   = '#5af78e'
yellow  = '#f3f99d'
blue    = '#57c7ff'
magenta = '#ff6ac1'
cyan    = '#9aedfe'
white   = '#f1f1f0'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#ff5c57'
green   = '#5af78e'
yellow  = '#f3f99d'
blue    = '#57c7ff'
magenta = '#ff6ac1'
cyan    = '#9aedfe'
white   = '#f1f1f0'

